services:
  - type: web
    name: ai-knowledge-assistant-api
    runtime: python

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn backend:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PRIMARY_LLM
        value: groq

      - key: FALLBACK_LLM
        value: groq

      - key: LLM_MODEL
        value: llama-3.1-8b-instant

      - key: CHROMA_DB_PATH
        value: ./chroma_db

      - key: COLLECTION_NAME
        value: ml_notes

      - key: TOP_K
        value: 3

      - key: SIMILARITY_THRESHOLD
        value: 1.3

      - key: GROQ_API_KEY
        sync: false